In [1]:
import numpy as np
import pandas as pd

In [2]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

In [253]:
movies.head(5000)

,id,title,overview,genres,keywords,cast_x,crew_x,cast,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron],"[Sam Worthington, Zoe Saldana, Sigourney Weave...","[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski],"[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux, Ralp...",[SamMendes],"[Daniel Craig, Christoph Waltz, Léa Seydoux, R...","[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman, Anne...",[ChristopherNolan],"[Christian Bale, Michael Caine, Gary Oldman, A...","[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton],"[Taylor Kitsch, Lynn Collins, Samantha Morton,...","[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...,...,...,...,...,...,...
4816,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui...","[Action, Crime, Thriller]","[unitedstates–mexicobarrier, legs, arms, paper...","[CarlosGallardo, JaimedeHoyos, PeterMarquardt,...",[RobertRodriguez],"[Carlos Gallardo, Jaime de Hoyos, Peter Marqua...","[El, Mariachi, just, wants, to, play, his, gui..."
4817,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended...","[Comedy, Romance]",[],"[EdwardBurns, KerryBishé, MarshaDietlein, Cait...",[EdwardBurns],"[Edward Burns, Kerry Bishé, Marsha Dietlein, C...","[A, newlywed, couple's, honeymoon, is, upended..."
4818,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,...","[Comedy, Drama, Romance, TVMovie]","[date, loveatfirstsight, narration, investigat...","[EricMabius, KristinBooth, CrystalLowe, GeoffG...",[ScottSmith],"[Eric Mabius, Kristin Booth, Crystal Lowe, Geo...","[""Signed,, Sealed,, Delivered"", introduces, a,..."
4819,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is...",[],[],"[DanielHenney, ElizaCoupe, BillPaxton, AlanRuc...",[DanielHsia],"[Daniel Henney, Eliza Coupe, Bill Paxton, Alan...","[When, ambitious, New, York, attorney, Sam, is..."
4820,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi...",[Documentary],"[obsession, camcorder, crush, dreamgirl]","[DrewBarrymore, BrianHerzlinger, CoreyFeldman,...",[BrianHerzlinger],"[Drew Barrymore, Brian Herzlinger, Corey Feldm...","[Ever, since, the, second, grade, when, he, fi..."

In [8]:
credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [12]:
movies=movies.merge(credits,on='title')

In [16]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4821 entries, 0 to 4820
Data columns (total 26 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4821 non-null   int64
 1   genres                4821 non-null   object
 2   homepage              1715 non-null   object
 3   id                    4821 non-null   int64
 4   keywords              4821 non-null   object
 5   original_language     4821 non-null   object
 6   original_title        4821 non-null   object
 7   overview              4818 non-null   object
 8   popularity            4821 non-null   float64
 9   production_companies  4821 non-null   object
 10  production_countries  4821 non-null   object
 11  release_date          4820 non-null   object
 12  revenue               4821 non-null   int64
 13  runtime               4819 non-null   float64
 14  spoken_languages      4821 non-null   object
 15  status                4821 non-null   object
 16  tagline               3977 non-null   object
 17  title                 4821 non-null   object
 18  vote_average          4821 non-null   float64
 19  vote_count            4821 non-null   int64
 20  movie_id_x            4821 non-null   int64
 21  cast_x                4821 non-null   object
 22  crew_x                4821 non-null   object
 23  movie_id_y            4821 non-null   int64
 24  cast_y                4821 non-null   object
 25  crew_y                4821 non-null   object
dtypes: float64(3), int64(6), object(17)
memory usage: 1016.9+ KB

In [39]:
# genres
# id
# keywords
# title
# overview
# tagline
# cast_x
# crew_x
# cast_y
# crew_y

movies = movies[['id','title','overview','genres','keywords','cast_x','crew_x']]

In [26]:
movies.head()

,id,title,overview,genres,keywords,cast_x,crew_x
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [47]:
movies.isnull().sum()

id          0
title       0
overview    0
genres      0
keywords    0
cast_x      0
crew_x      0
dtype: int64

In [46]:
movies.dropna(inplace=True)

In [54]:
movies.duplicated().sum()

12

In [56]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [57]:
#'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'
#['Action','Adventure','Fantasy', 'SciFi']

In [87]:
import ast
def convert(obj):
    L = []
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [89]:
movies['genres'] = movies['genres'].apply(convert)

ValueError: malformed node or string: ['Action', 'Adventure', 'Fantasy', 'Science Fiction']

In [84]:
movies.head()

,id,title,overview,genres,keywords,cast_x,crew_x
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [104]:
movies['keywords'] = movies['keywords'].apply(convert)

ValueError: malformed node or string: ['culture clash', 'future', 'space war', 'space colony', 'society', 'space travel', 'futuristic', 'romance', 'space', 'alien', 'tribe', 'alien planet', 'cgi', 'marine', 'soldier', 'battle', 'love affair', 'anti war', 'power relations', 'mind and soul', '3d']

In [90]:
movies.head()

,id,title,overview,genres,keywords,cast_x,crew_x
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [95]:
movies['cast_x'][0]

'[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]'

In [98]:
import ast
def convert3(obj):
    L = []
    counter = 0
    for i in ast.literal_eval(obj):
        if counter != 3:
            L.append(i['name'])
            counter = +1
        else:
            break
    return L

In [103]:
movies['cast_x'].apply(convert3)

0       [Sam Worthington, Zoe Saldana, Sigourney Weave...
1       [Johnny Depp, Orlando Bloom, Keira Knightley, ...
2       [Daniel Craig, Christoph Waltz, Léa Seydoux, R...
3       [Christian Bale, Michael Caine, Gary Oldman, A...
4       [Taylor Kitsch, Lynn Collins, Samantha Morton,...
                              ...
4816    [Carlos Gallardo, Jaime de Hoyos, Peter Marqua...
4817    [Edward Burns, Kerry Bishé, Marsha Dietlein, C...
4818    [Eric Mabius, Kristin Booth, Crystal Lowe, Geo...
4819    [Daniel Henney, Eliza Coupe, Bill Paxton, Alan...
4820    [Drew Barrymore, Brian Herzlinger, Corey Feldm...
Name: cast_x, Length: 4818, dtype: object

In [110]:
movies['cast_x'] = movies['cast_x'].apply(convert3)

In [111]:
movies.head()

,id,title,overview,genres,keywords,cast_x,crew_x,cast
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...","[Sam Worthington, Zoe Saldana, Sigourney Weave..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...","[Johnny Depp, Orlando Bloom, Keira Knightley, ..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...","[Christian Bale, Michael Caine, Gary Oldman, A..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...","[Taylor Kitsch, Lynn Collins, Samantha Morton,..."

In [115]:
movies['crew_x'][0]

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "department": 

In [118]:
 def fetch_director(obj):
        L = []
        for i in ast.literal_eval(obj):
            if i['job'] == 'Director':
                L.append(i['name'])
                break
        return L

In [122]:
movies['crew_x'].apply(fetch_director)

0           [James Cameron]
1          [Gore Verbinski]
2              [Sam Mendes]
3       [Christopher Nolan]
4          [Andrew Stanton]
               ...
4816     [Robert Rodriguez]
4817         [Edward Burns]
4818          [Scott Smith]
4819          [Daniel Hsia]
4820     [Brian Herzlinger]
Name: crew_x, Length: 4818, dtype: object

In [123]:
movies['crew_x'] = movies['crew_x'].apply(fetch_director)

In [124]:
movies.head()

,id,title,overview,genres,keywords,cast_x,crew_x,cast
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron],"[Sam Worthington, Zoe Saldana, Sigourney Weave..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski],"[Johnny Depp, Orlando Bloom, Keira Knightley, ..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...",[Sam Mendes],"[Daniel Craig, Christoph Waltz, Léa Seydoux, R..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...",[Christopher Nolan],"[Christian Bale, Michael Caine, Gary Oldman, A..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...",[Andrew Stanton],"[Taylor Kitsch, Lynn Collins, Samantha Morton,..."

In [125]:
movies['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [126]:
movies['overview'].apply(lambda x:x.split())

0       [In, the, 22nd, century,, a, paraplegic, Marin...
1       [Captain, Barbossa,, long, believed, to, be, d...
2       [A, cryptic, message, from, Bond’s, past, send...
3       [Following, the, death, of, District, Attorney...
4       [John, Carter, is, a, war-weary,, former, mili...
                              ...
4816    [El, Mariachi, just, wants, to, play, his, gui...
4817    [A, newlywed, couple's, honeymoon, is, upended...
4818    ["Signed,, Sealed,, Delivered", introduces, a,...
4819    [When, ambitious, New, York, attorney, Sam, is...
4820    [Ever, since, the, second, grade, when, he, fi...
Name: overview, Length: 4818, dtype: object

In [127]:
movies['overview']=movies['overview'].apply(lambda x:x.split())

In [131]:
movies.head()

,id,title,overview,genres,keywords,cast_x,crew_x,cast
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron],"[Sam Worthington, Zoe Saldana, Sigourney Weave..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski],"[Johnny Depp, Orlando Bloom, Keira Knightley, ..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...",[Sam Mendes],"[Daniel Craig, Christoph Waltz, Léa Seydoux, R..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...",[Christopher Nolan],"[Christian Bale, Michael Caine, Gary Oldman, A..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...",[Andrew Stanton],"[Taylor Kitsch, Lynn Collins, Samantha Morton,..."

In [132]:
movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])

0       [Action, Adventure, Fantasy, ScienceFiction]
1                       [Adventure, Fantasy, Action]
2                         [Action, Adventure, Crime]
3                   [Action, Crime, Drama, Thriller]
4                [Action, Adventure, ScienceFiction]
                            ...
4816                       [Action, Crime, Thriller]
4817                               [Comedy, Romance]
4818               [Comedy, Drama, Romance, TVMovie]
4819                                              []
4820                                   [Documentary]
Name: genres, Length: 4818, dtype: object

In [134]:
movies['genres'] = movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])  
movies['cast_x'] = movies['cast_x'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew_x'] = movies['crew_x'].apply(lambda x:[i.replace(" ","") for i in x])

In [135]:
movies.head()

,id,title,overview,genres,keywords,cast_x,crew_x,cast
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron],"[Sam Worthington, Zoe Saldana, Sigourney Weave..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski],"[Johnny Depp, Orlando Bloom, Keira Knightley, ..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux, Ralp...",[SamMendes],"[Daniel Craig, Christoph Waltz, Léa Seydoux, R..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman, Anne...",[ChristopherNolan],"[Christian Bale, Michael Caine, Gary Oldman, A..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton],"[Taylor Kitsch, Lynn Collins, Samantha Morton,..."

In [136]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast_x'] + movies['crew_x']

In [137]:
movies.head()

,id,title,overview,genres,keywords,cast_x,crew_x,cast,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron],"[Sam Worthington, Zoe Saldana, Sigourney Weave...","[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski],"[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux, Ralp...",[SamMendes],"[Daniel Craig, Christoph Waltz, Léa Seydoux, R...","[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman, Anne...",[ChristopherNolan],"[Christian Bale, Michael Caine, Gary Oldman, A...","[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton],"[Taylor Kitsch, Lynn Collins, Samantha Morton,...","[John, Carter, is, a, war-weary,, former, mili..."

In [139]:
new_df = movies[['id','title' , 'tags']]

In [140]:
new_df

,id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
4816,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui..."
4817,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended..."
4818,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,..."
4819,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is..."
4820,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi..."

In [142]:
new_df['tags'].apply(lambda x: " ".join(x))

0       In the 22nd century, a paraplegic Marine is di...
1       Captain Barbossa, long believed to be dead, ha...
2       A cryptic message from Bond’s past sends him o...
3       Following the death of District Attorney Harve...
4       John Carter is a war-weary, former military ca...
                              ...
4816    El Mariachi just wants to play his guitar and ...
4817    A newlywed couple's honeymoon is upended by th...
4818    "Signed, Sealed, Delivered" introduces a dedic...
4819    When ambitious New York attorney Sam is sent t...
4820    Ever since the second grade when he first saw ...
Name: tags, Length: 4818, dtype: object

In [143]:
new_df['tags']=new_df['tags'].apply(lambda x: " ".join(x))

C:\Users\ASUS\AppData\Local\Temp\ipykernel_17620\684433085.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x: " ".join(x))

In [144]:
new_df

,id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."
...,...,...,...
4816,9367,El Mariachi,El Mariachi just wants to play his guitar and ...
4817,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...
4818,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic..."
4819,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...
4820,25975,My Date with Drew,Ever since the second grade when he first saw ...

In [146]:
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver StephenLang MichelleRodriguez GiovanniRibisi JoelDavidMoore CCHPounder WesStudi LazAlonso DileepRao MattGerald SeanAnthonyMoran JasonWhyte ScottLawrence KellyKilgour JamesPatrickPitt SeanPatrickMurphy PeterDillon KevinDorman KelsonHenderson DavidVanHorn JacobTomuri MichaelBlain-Rozgay JonCurry LukeHawker WoodySchultz PeterMensah SoniaYee JahnelCurfman IlramChoi KylaWarren LisaRoumain DebraWilson ChrisMala TaylorKibby JodieLandau JulieLamm CullenB.Madden JosephBradyMadden FrankieTorres AustinWilson SaraWilson TamicaWashington-Miller LucyBriant NathanMeister GerryBlair MatthewChamberlain PaulYates WrayWilson JamesGaylyn MelvinLenoClarkIII CarvonFutrell BrandonJelkes MicahMoch HanniyahMuhammad ChristopherNolen ChristaOliver AprilMarieThomas BravitaA.Threatt ColinBleasdale MikeBodnar MattClayton NicoleDionne JamieHarrison AllanHenry AnthonyIngruber AshleyJeffery DeanKnowsley JosephMika-Hunt TerryNotary KaiPantano LoganPithyou StuartPollock Raja GarethRuck RhianSheehan T.J.Storm JodieTaylor AliciaVela-Bailey RichardWhiteside NikieZambo JuleneRenee JamesCameron'

In [147]:
new_df['tags'].apply(lambda x:x.lower())

0       in the 22nd century, a paraplegic marine is di...
1       captain barbossa, long believed to be dead, ha...
2       a cryptic message from bond’s past sends him o...
3       following the death of district attorney harve...
4       john carter is a war-weary, former military ca...
                              ...
4816    el mariachi just wants to play his guitar and ...
4817    a newlywed couple's honeymoon is upended by th...
4818    "signed, sealed, delivered" introduces a dedic...
4819    when ambitious new york attorney sam is sent t...
4820    ever since the second grade when he first saw ...
Name: tags, Length: 4818, dtype: object

In [149]:
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

C:\Users\ASUS\AppData\Local\Temp\ipykernel_17620\3214958533.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

In [155]:
new_df.head()

,id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [151]:
new_df['tags'][0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver stephenlang michellerodriguez giovanniribisi joeldavidmoore cchpounder wesstudi lazalonso dileeprao mattgerald seananthonymoran jasonwhyte scottlawrence kellykilgour jamespatrickpitt seanpatrickmurphy peterdillon kevindorman kelsonhenderson davidvanhorn jacobtomuri michaelblain-rozgay joncurry lukehawker woodyschultz petermensah soniayee jahnelcurfman ilramchoi kylawarren lisaroumain debrawilson chrismala taylorkibby jodielandau julielamm cullenb.madden josephbradymadden frankietorres austinwilson sarawilson tamicawashington-miller lucybriant nathanmeister gerryblair matthewchamberlain paulyates wraywilson jamesgaylyn melvinlenoclarkiii carvonfutrell brandonjelkes micahmoch hanniyahmuhammad christophernolen christaoliver aprilmariethomas bravitaa.threatt colinbleasdale mikebodnar mattclayton nicoledionne jamieharrison allanhenry anthonyingruber ashleyjeffery deanknowsley josephmika-hunt terrynotary kaipantano loganpithyou stuartpollock raja garethruck rhiansheehan t.j.storm jodietaylor aliciavela-bailey richardwhiteside nikiezambo julenerenee jamescameron'

In [152]:
new_df['tags'][11]

"quantum of solace continues the adventures of james bond after casino royale. betrayed by vesper, the woman he loved, 007 fights the urge to make his latest mission personal. pursuing his determination to uncover the truth, bond and m interrogate mr. white, who reveals that the organization that blackmailed vesper is far more complex and dangerous than anyone had imagined. adventure action thriller crime killing undercover secretagent britishsecretservice danielcraig olgakurylenko mathieuamalric judidench giancarlogiannini gemmaarterton jeffreywright davidharbour jesperchristensen anatoletaubman rorykinnear timpigott-smith joaquíncosio glennfoster paulritter stanakatic lucrezialantedellarovere neiljackson oonachaplin rachelmcdowall gustavonanez markwakeling sarahhadland daviddecio aaronking alexandraprusa brandonjovanovich alexandrekrawetz fernandoguilléncuervo jesúsochoa simonkassianides brendano'hea marcforster"

In [156]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 5000,stop_words ='english')

In [176]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [177]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [178]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [179]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [188]:
len(cv.get_feature_names())

AttributeError: 'CountVectorizer' object has no attribute 'get_features_name'

In [189]:
cv.get_feature_names()

AttributeError: 'CountVectorizer' object has no attribute 'get_feature_names'

In [190]:
!pip install nltk

Requirement already satisfied: nltk in c:\users\asus\anaconda3\anaconda\lib\site-packages (3.7)
Requirement already satisfied: regex>=2021.8.3 in c:\users\asus\anaconda3\anaconda\lib\site-packages (from nltk) (2022.7.9)
Requirement already satisfied: click in c:\users\asus\anaconda3\anaconda\lib\site-packages (from nltk) (8.0.4)
Requirement already satisfied: joblib in c:\users\asus\anaconda3\anaconda\lib\site-packages (from nltk) (1.1.1)
Requirement already satisfied: tqdm in c:\users\asus\anaconda3\anaconda\lib\site-packages (from nltk) (4.64.1)
Requirement already satisfied: colorama in c:\users\asus\anaconda3\anaconda\lib\site-packages (from click->nltk) (0.4.6)

In [191]:
import nltk

In [195]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [196]:
def stem(stem):
    y = []
    for i in text.split():
        ps.stem(i)

In [197]:
ps.stem('loved')

'love'

In [198]:
ps.stem('hugging')

'hug'

In [203]:
def stem(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [204]:
new_df['tags'][0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver stephenlang michellerodriguez giovanniribisi joeldavidmoore cchpounder wesstudi lazalonso dileeprao mattgerald seananthonymoran jasonwhyte scottlawrence kellykilgour jamespatrickpitt seanpatrickmurphy peterdillon kevindorman kelsonhenderson davidvanhorn jacobtomuri michaelblain-rozgay joncurry lukehawker woodyschultz petermensah soniayee jahnelcurfman ilramchoi kylawarren lisaroumain debrawilson chrismala taylorkibby jodielandau julielamm cullenb.madden josephbradymadden frankietorres austinwilson sarawilson tamicawashington-miller lucybriant nathanmeister gerryblair matthewchamberlain paulyates wraywilson jamesgaylyn melvinlenoclarkiii carvonfutrell brandonjelkes micahmoch hanniyahmuhammad christophernolen christaoliver aprilmariethomas bravitaa.threatt colinbleasdale mikebodnar mattclayton nicoledionne jamieharrison allanhenry anthonyingruber ashleyjeffery deanknowsley josephmika-hunt terrynotary kaipantano loganpithyou stuartpollock raja garethruck rhiansheehan t.j.storm jodietaylor aliciavela-bailey richardwhiteside nikiezambo julenerenee jamescameron'

In [205]:
stem('in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver stephenlang michellerodriguez giovanniribisi joeldavidmoore cchpounder wesstudi lazalonso dileeprao mattgerald seananthonymoran jasonwhyte scottlawrence kellykilgour jamespatrickpitt seanpatrickmurphy peterdillon kevindorman kelsonhenderson davidvanhorn jacobtomuri michaelblain-rozgay joncurry lukehawker woodyschultz petermensah soniayee jahnelcurfman ilramchoi kylawarren lisaroumain debrawilson chrismala taylorkibby jodielandau julielamm cullenb.madden josephbradymadden frankietorres austinwilson sarawilson tamicawashington-miller lucybriant nathanmeister gerryblair matthewchamberlain paulyates wraywilson jamesgaylyn melvinlenoclarkiii carvonfutrell brandonjelkes micahmoch hanniyahmuhammad christophernolen christaoliver aprilmariethomas bravitaa.threatt colinbleasdale mikebodnar mattclayton nicoledionne jamieharrison allanhenry anthonyingruber ashleyjeffery deanknowsley josephmika-hunt terrynotary kaipantano loganpithyou stuartpollock raja garethruck rhiansheehan t.j.storm jodietaylor aliciavela-bailey richardwhiteside nikiezambo julenerenee jamescameron')

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d samworthington zoesaldana sigourneyweav stephenlang michellerodriguez giovanniribisi joeldavidmoor cchpounder wesstudi lazalonso dileeprao mattgerald seananthonymoran jasonwhyt scottlawr kellykilgour jamespatrickpitt seanpatrickmurphi peterdillon kevindorman kelsonhenderson davidvanhorn jacobtomuri michaelblain-rozgay joncurri lukehawk woodyschultz petermensah soniaye jahnelcurfman ilramchoi kylawarren lisaroumain debrawilson chrismala taylorkibbi jodielandau julielamm cullenb.madden josephbradymadden frankietorr austinwilson sarawilson tamicawashington-mil lucybri nathanmeist gerryblair matthewchamberlain paulyat wraywilson jamesgaylyn melvinlenoclarkiii carvonfutrel brandonjelk micahmoch hanniyahmuhammad christophernolen christaoliv aprilmariethoma bravitaa.threatt colinbleasdal mikebodnar mattclayton nicoledionn jamieharrison allanhenri anthonyingrub ashleyjefferi deanknowsley josephmika-hunt terrynotari kaipantano loganpithy stuartpollock raja garethruck rhiansheehan t.j.storm jodietaylor aliciavela-bailey richardwhitesid nikiezambo julenerene jamescameron'

In [206]:
new_df['tags'].apply(stem)

0       in the 22nd century, a parapleg marin is dispa...
1       captain barbossa, long believ to be dead, ha c...
2       a cryptic messag from bond’ past send him on a...
3       follow the death of district attorney harvey d...
4       john carter is a war-weary, former militari ca...
                              ...
4816    el mariachi just want to play hi guitar and ca...
4817    a newlyw couple' honeymoon is upend by the arr...
4818    "signed, sealed, delivered" introduc a dedic q...
4819    when ambiti new york attorney sam is sent to s...
4820    ever sinc the second grade when he first saw h...
Name: tags, Length: 4818, dtype: object

In [207]:
new_df['tags'] = new_df['tags'].apply(stem)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_17620\3213734980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [208]:
from sklearn.metrics.pairwise import cosine_similarity

In [209]:
cosine_similarity(vectors)

array([[1.        , 0.07144883, 0.05083286, ..., 0.02325581, 0.02541643,
        0.        ],
       [0.07144883, 1.        , 0.07808688, ..., 0.02381628, 0.        ,
        0.        ],
       [0.05083286, 0.07808688, 1.        , ..., 0.02541643, 0.        ,
        0.        ],
       ...,
       [0.02325581, 0.02381628, 0.02541643, ..., 1.        , 0.07624929,
        0.05083286],
       [0.02541643, 0.        , 0.        , ..., 0.07624929, 1.        ,
        0.05555556],
       [0.        , 0.        , 0.        , ..., 0.05083286, 0.05555556,
        1.        ]])

In [210]:
cosine_similarity(vectors).shape

(4818, 4818)

In [211]:
similarity = cosine_similarity(vectors)

In [218]:
similarity[0]

array([1.        , 0.07144883, 0.05083286, ..., 0.02325581, 0.02541643,
       0.        ])

In [219]:
def recommend(movie):
    return

In [220]:
new_df[new_df['title'] == 'Batman Begins'].index[0]

119

In [224]:
def recommend(movie):
    movie_index = new_df[new_df['title'] == 'Batman Begins'].index[0]
    distances = similarity[movie_index]
    return

In [226]:
sorted(list(enumerate(similarity[0])),reverse=True, key=lambda x:x[1])

[(0, 1.0),
 (1928, 0.23199266800191015),
 (1220, 0.230220812479341),
 (582, 0.2282766956670531),
 (539, 0.22264681319788207),
 (507, 0.21656228851349335),
 (3616, 0.2114774672189068),
 (1452, 0.21147746721890678),
 (4204, 0.20991342856239587),
 (260, 0.20922631238637657),
 (74, 0.20691022044226628),
 (83, 0.2001978239850581),
 (2979, 0.19606959042763455),
 (3742, 0.1950768266287065),
 (47, 0.19242064284886287),
 (495, 0.19078890022466805),
 (2341, 0.1903297204970161),
 (1208, 0.18824832213400472),
 (972, 0.1882483221340047),
 (973, 0.1882483221340047),
 (322, 0.18604651162790697),
 (2417, 0.18392019594868114),
 (1545, 0.1830730233380795),
 (1198, 0.18307302333807945),
 (61, 0.1829982843991256),
 (36, 0.18186515719212626),
 (2212, 0.18043874177926345),
 (3546, 0.18043874177926345),
 (3335, 0.1797212886723974),
 (2794, 0.17944458136637376),
 (974, 0.1779149987213721),
 (975, 0.1779149987213721),
 (4417, 0.1760901812651248),
 (1325, 0.17492785713532988),
 (4060, 0.17430604019629448),
 (1333, 0.1729171253112705),
 (942, 0.1709352016769265),
 (151, 0.17049858486761837),
 (466, 0.1699096415365797),
 (3007, 0.16918197377512542),
 (3170, 0.16918197377512542),
 (184, 0.16878498775964426),
 (2739, 0.16638958140993046),
 (150, 0.16522803435465708),
 (305, 0.16404358872971006),
 (27, 0.16302782918784448),
 (461, 0.16256402219058874),
 (220, 0.1617491598051576),
 (1348, 0.1617491598051576),
 (301, 0.1595483884167619),
 (1279, 0.1592795619605697),
 (4, 0.1591320125431105),
 (158, 0.15882898238187504),
 (1681, 0.15749984619163154),
 (581, 0.15564320159117262),
 (931, 0.1546617786679401),
 (300, 0.1540789086069842),
 (1075, 0.1540789086069842),
 (373, 0.15249857033260467),
 (4022, 0.15249857033260467),
 (46, 0.15096588248481377),
 (1205, 0.15042366316917005),
 (661, 0.15017021115565554),
 (1404, 0.14947849761564372),
 (1839, 0.1494784976156437),
 (838, 0.1468693638708063),
 (3362, 0.1467418177209373),
 (3630, 0.14651588715165131),
 (108, 0.1452669881517611),
 (1953, 0.14467284665112365),
 (208, 0.1437770309379179),
 (502, 0.1428976524688623),
 (56, 0.14159136794714974),
 (2504, 0.14159136794714974),
 (2523, 0.14159136794714974),
 (3636, 0.14159136794714974),
 (1391, 0.14118624160050353),
 (4348, 0.14118624160050353),
 (1973, 0.13897535958414065),
 (149, 0.1381365031419941),
 (168, 0.13794014696151086),
 (1816, 0.13794014696151086),
 (2083, 0.13694775891619418),
 (2177, 0.13694775891619418),
 (7, 0.13667808797729797),
 (1359, 0.1363988678940947),
 (1224, 0.13490812512398637),
 (1946, 0.13490812512398637),
 (1182, 0.134790966504298),
 (1496, 0.13311166512794437),
 (2978, 0.13311166512794437),
 (139, 0.13240583787506852),
 (67, 0.1320676359488436),
 (91, 0.13076644524148534),
 (332, 0.13076644524148534),
 (577, 0.13076644524148534),
 (2694, 0.13076644524148534),
 (1840, 0.13071306028508972),
 (311, 0.1307130602850897),
 (84, 0.13041465921865672),
 (490, 0.130051217752471),
 (1331, 0.130051217752471),
 (4011, 0.130051217752471),
 (26, 0.12939932784412608),
 (1326, 0.12939932784412608),
 (1301, 0.1281244265276946),
 (17, 0.1275894579008856),
 (1729, 0.12719260014977868),
 (2592, 0.12719260014977868),
 (31, 0.1270821419438372),
 (568, 0.1270821419438372),
 (687, 0.1270821419438372),
 (1303, 0.1270821419438372),
 (206, 0.1256837377335324),
 (2141, 0.1256837377335324),
 (422, 0.12451456127293808),
 (487, 0.12451456127293808),
 (2628, 0.12451456127293808),
 (4502, 0.12451456127293808),
 (41, 0.12451456127293806),
 (557, 0.12369267399882337),
 (3417, 0.12369267399882337),
 (2881, 0.12337741817289974),
 (127, 0.12244949999473093),
 (342, 0.1224494999947309),
 (1723, 0.12227087189088336),
 (413, 0.12209657262637609),
 (595, 0.12209657262637608),
 (505, 0.12199885626608374),
 (3687, 0.12056070554260302),
 (157, 0.11962972091091584),
 (1051, 0.11962972091091584),
 (1755, 0.11962972091091584),
 (2488, 0.11812488464372366),
 (199, 0.11812488464372364),
 (454, 0.11765520133375293),
 (1041, 0.11765520133375293),
 (3415, 0.11765520133375292),
 (2386, 0.11739345417674985),
 (111, 0.11627906976744186),
 (187, 0.11627906976744186),
 (1749, 0.11620402679752967),
 (172, 0.11527808354084698),
 (368, 0.11527808354084698),
 (1006, 0.11527808354084698),
 (1666, 0.11527808354084698),
 (4215, 0.1143739277494535),
 (4360, 0.1143739277494535),
 (94, 0.11366572324507891),
 (228, 0.11366572324507891),
 (1019, 0.11366572324507891),
 (1625, 0.11366572324507891),
 (2721, 0.11366572324507891),
 (939, 0.11349071817863016),
 (2876, 0.1132730943577198),
 (4685, 0.1132730943577198),
 (238, 0.11262765836674166),
 (420, 0.11242343760332196),
 (249, 0.1113692092779409),
 (1841, 0.1113692092779409),
 (3384, 0.1113692092779409),
 (549, 0.11122101332503227),
 (740, 0.11122101332503227),
 (432, 0.11005636329070301),
 (3317, 0.110056363290703),
 (3638, 0.110056363290703),
 (50, 0.10955820713295535),
 (3155, 0.10936239248647338),
 (270, 0.10892755023757476),
 (123, 0.10892755023757475),
 (2555, 0.10892755023757475),
 (1281, 0.10783277320343843),
 (3675, 0.10783277320343843),
 (134, 0.10783277320343841),
 (778, 0.10783277320343841),
 (1035, 0.10783277320343841),
 (1100, 0.10783277320343841),
 (1278, 0.10783277320343841),
 (4109, 0.10783277320343841),
 (43, 0.1078327732034384),
 (1520, 0.1078327732034384),
 (28, 0.10618637464037979),
 (148, 0.10618637464037979),
 (232, 0.10618637464037979),
 (859, 0.10618637464037979),
 (52, 0.10573873360945339),
 (95, 0.10573873360945338),
 (1487, 0.10573873360945338),
 (1582, 0.10495671428119793),
 (627, 0.10495671428119792),
 (1305, 0.10495671428119792),
 (1381, 0.10495671428119792),
 (3733, 0.10495671428119792),
 (4557, 0.10473644811127698),
 (544, 0.10461315619318828),
 (1277, 0.10461315619318828),
 (425, 0.10376213439411505),
 (81, 0.10360237735649558),
 (88, 0.1031078524452934),
 (483, 0.1031078524452934),
 (746, 0.1031078524452934),
 (1990, 0.1031078524452934),
 (2458, 0.1031078524452934),
 (2591, 0.1031078524452934),
 (3506, 0.1031078524452934),
 (3628, 0.1031078524452934),
 (4091, 0.1031078524452934),
 (2447, 0.10281451514408312),
 (2768, 0.10281451514408312),
 (160, 0.10229915092057103),
 (653, 0.10229915092057101),
 (808, 0.10229915092057101),
 (2529, 0.10229915092057101),
 (2642, 0.10229915092057101),
 (4012, 0.10229915092057101),
 (239, 0.1018923932424028),
 (10, 0.10166571355506977),
 (87, 0.10166571355506977),
 (275, 0.10166571355506977),
 (1298, 0.10166571355506977),
 (2080, 0.10166571355506977),
 (777, 0.10099464540584711),
 (1023, 0.10099464540584711),
 (294, 0.10028244211278005),
 (579, 0.10028244211278005),
 (3110, 0.10028244211278005),
 (102, 0.10012021643290915),
 (692, 0.10012021643290915),
 (141, 0.09983374884595828),
 (1160, 0.09983374884595828),
 (2770, 0.09983374884595828),
 (3793, 0.09983374884595828),
 (4030, 0.09983374884595828),
 (4210, 0.09983374884595828),
 (18, 0.0992681139886719),
 (166, 0.0989541391990587),
 (1294, 0.0989541391990587),
 (1409, 0.0989541391990587),
 (2189, 0.0989541391990587),
 (3348, 0.0989541391990587),
 (169, 0.09843740386976971),
 (2114, 0.09843740386976971),
 (68, 0.09767725810110087),
 (122, 0.09767725810110087),
 (266, 0.09767725810110087),
 (535, 0.09767725810110087),
 (754, 0.09767725810110087),
 (854, 0.09767725810110087),
 (900, 0.09767725810110087),
 (992, 0.09767725810110087),
 (1113, 0.09767725810110087),
 (1179, 0.09767725810110087),
 (193, 0.09762720569806997),
 (773, 0.09753841331435326),
 (1532, 0.09753841331435326),
 (2267, 0.09753841331435326),
 (2331, 0.09753841331435326),
 (3851, 0.09753841331435326),
 (4343, 0.09753841331435326),
 (4635, 0.09753841331435326),
 (203, 0.09644856443408242),
 (312, 0.09644856443408242),
 (513, 0.09644856443408242),
 (787, 0.09644856443408242),
 (1086, 0.09644856443408242),
 (2021, 0.09644856443408242),
 (3795, 0.09644856443408242),
 (4242, 0.09644856443408242),
 (213, 0.09606506961737248),
 (951, 0.09539445011233401),
 (1583, 0.09539445011233401),
 (1735, 0.09539445011233401),
 (2659, 0.09539445011233401),
 (2669, 0.09539445011233401),
 (1090, 0.09526510164590819),
 (1162, 0.09526510164590819),
 (1199, 0.09526510164590819),
 (153, 0.0945755984821918),
 (72, 0.09412416106700235),
 (131, 0.09412416106700235),
 (1206, 0.09412416106700235),
 (1831, 0.09412416106700235),
 (3451, 0.09412416106700235),
 (3472, 0.09412416106700235),
 (2604, 0.09412416106700233),
 (624, 0.09338592095470356),
 (660, 0.09338592095470356),
 (3063, 0.09338592095470356),
 (3748, 0.09338592095470356),
 (14, 0.09302325581395349),
 (174, 0.09302325581395349),
 (295, 0.09302325581395349),
 (334, 0.09302325581395349),
 (510, 0.09302325581395349),
 (1060, 0.09302325581395349),
 (3016, 0.09302325581395349),
 (371, 0.09196009797434057),
 (2396, 0.09196009797434057),
 (3148, 0.09196009797434057),
 (2570, 0.0914991421995628),
 (3101, 0.0914991421995628),
 (3966, 0.0914991421995628),
 (4268, 0.0914991421995628),
 (403, 0.09113532707206115),
 (785, 0.09113532707206114),
 (85, 0.09104504936087722),
 (307, 0.0910450493608772),
 (529, 0.09093257859606313),
 (5, 0.09049125308576025),
 (410, 0.08993875008265757),
 (508, 0.08993875008265757),
 (898, 0.08993875008265757),
 (1237, 0.08993875008265757),
 (1854, 0.08993875008265757),
 (1932, 0.08993875008265757),
 (715, 0.08972229068318688),
 (794, 0.08972229068318688),
 (1081, 0.08972229068318688),
 (1509, 0.08972229068318688),
 (1597, 0.08972229068318688),
 (1694, 0.08972229068318688),
 (2464, 0.08972229068318688),
 (2660, 0.08972229068318688),
 (4147, 0.08972229068318688),
 (126, 0.08897681066002582),
 (257, 0.08897681066002582),
 (933, 0.08897681066002582),
 (278, 0.0880450906325624),
 (330, 0.0880450906325624),
 (643, 0.0880450906325624),
 (2282, 0.0880450906325624),
 (2292, 0.0880450906325624),
 (2804, 0.0880450906325624),
 (4057, 0.0880450906325624),
 (4653, 0.0880450906325624),
 (4666, 0.0880450906325624),
 (476, 0.08804509063256238),
 (922, 0.08804509063256238),
 (1284, 0.08804509063256238),
 (1416, 0.08804509063256238),
 (2668, 0.08804509063256238),
 (479, 0.08804509063256237),
 (1093, 0.08746392856766494),
 (279, 0.0871420401900598),
 (412, 0.0871420401900598),
 (870, 0.0871420401900598),
 (564, 0.08645856265563523),
 (791, 0.08645856265563523),
 (937, 0.08645856265563523),
 (1310, 0.08645856265563523),
 (2404, 0.08645856265563523),
 (3305, 0.08645856265563523),
 (4480, 0.08645856265563523),
 (596, 0.08626621856275073),
 (813, 0.08626621856275073),
 (1034, 0.08626621856275073),
 (129, 0.0854162843517964),
 (182, 0.0854162843517964),
 (589, 0.0854162843517964),
 (1001, 0.0854162843517964),
 (1282, 0.0854162843517964),
 (1361, 0.0854162843517964),
 (799, 0.08524929243380919),
 (167, 0.08495482076828985),
 (292, 0.08495482076828985),
 (369, 0.08495482076828985),
 (389, 0.08495482076828985),
 (786, 0.08495482076828985),
 (935, 0.08495482076828985),
 (1482, 0.08495482076828985),
 (2101, 0.08495482076828985),
 (2255, 0.08495482076828985),
 (2825, 0.08495482076828985),
 (2848, 0.08495482076828985),
 (45, 0.08459098688756271),
 (253, 0.08459098688756271),
 (1447, 0.08459098688756271),
 (2011, 0.08459098688756271),
 (2496, 0.08459098688756271),
 (4528, 0.08459098688756271),
 (467, 0.08378915848902159),
 (607, 0.08378915848902159),
 (2013, 0.08378915848902159),
 (142, 0.08352690695845567),
 (306, 0.08352690695845567),
 (356, 0.08352690695845567),
 (400, 0.08352690695845567),
 (960, 0.08352690695845567),
 (1764, 0.08352690695845567),
 (3436, 0.08352690695845567),
 (3545, 0.08352690695845567),
 (4638, 0.08352690695845567),
 (107, 0.08300970751529205),
 (222, 0.08300970751529205),
 (473, 0.08300970751529205),
 (243, 0.08225161211526649),
 (612, 0.08225161211526649),
 (2976, 0.08225161211526649),
 (233, 0.08216865534971651),
 (315, 0.08216865534971651),
 (781, 0.08216865534971651),
 (901, 0.08216865534971651),
 (920, 0.08216865534971651),
 (1008, 0.08216865534971651),
 (1594, 0.08216865534971651),
 (3828, 0.08216865534971651),
 (3938, 0.08216865534971651),
 (4271, 0.08216865534971651),
 (92, 0.08151391459392224),
 (1280, 0.08151391459392224),
 (1505, 0.08151391459392224),
 (3162, 0.08151391459392224),
 (3226, 0.08151391459392224),
 (4365, 0.08151391459392224),
 (4749, 0.08151391459392224),
 (164, 0.0808745799025788),
 (263, 0.0808745799025788),
 (1386, 0.0808745799025788),
 (1531, 0.0808745799025788),
 (1568, 0.0808745799025788),
 (2175, 0.0808745799025788),
 (4669, 0.0808745799025788),
 (618, 0.08079571632467769),
 (1504, 0.08079571632467769),
 (1886, 0.08079571632467769),
 (3449, 0.08079571632467769),
 (2107, 0.08079571632467768),
 (491, 0.08009617314632732),
 (1426, 0.08009617314632732),
 (1495, 0.08009617314632732),
 (75, 0.07963978098028485),
 (236, 0.07963978098028485),
 (349, 0.07963978098028485),
 (511, 0.07963978098028485),
 (691, 0.07963978098028485),
 (984, 0.07963978098028485),
 (1211, 0.07963978098028485),
 (1708, 0.07963978098028485),
 (1798, 0.07963978098028485),
 (2259, 0.07963978098028485),
 (2261, 0.07963978098028485),
 (2802, 0.07963978098028485),
 (3036, 0.07963978098028485),
 (3309, 0.07963978098028485),
 (3318, 0.07963978098028485),
 (3431, 0.07963978098028485),
 (3922, 0.07963978098028485),
 (2456, 0.07949537509361168),
 (1836, 0.07941449119093752),
 (2506, 0.07941449119093752),
 (2394, 0.07906682547518068),
 (170, 0.07874992309581577),
 (768, 0.07874992309581577),
 (2888, 0.07874992309581577),
 (3261, 0.07874992309581577),
 (3439, 0.07874992309581577),
 (3961, 0.07874992309581577),
 (4073, 0.07874992309581577),
 (4504, 0.07874992309581577),
 (4514, 0.07874992309581577),
 (35, 0.07845986714489121),
 (271, 0.07845986714489121),
 (325, 0.07845986714489121),
 (530, 0.07845986714489121),
 (775, 0.07845986714489121),
 (814, 0.07845986714489121),
 (1146, 0.07845986714489121),
 (1253, 0.07845986714489121),
 (2652, 0.07845986714489121),
 (3243, 0.07845986714489121),
 (103, 0.07810176455845598),
 (812, 0.07810176455845598),
 (1286, 0.07810176455845598),
 (1350, 0.07810176455845598),
 (1413, 0.07810176455845598),
 (1906, 0.07810176455845598),
 (230, 0.0774693511983531),
 (363, 0.0774693511983531),
 (1647, 0.0774693511983531),
 (12, 0.07733088933397005),
 (21, 0.07733088933397005),
 (23, 0.07733088933397005),
 (33, 0.07733088933397005),
 (112, 0.07733088933397005),
 (207, 0.07733088933397005),
 (227, 0.07733088933397005),
 (241, 0.07733088933397005),
 (894, 0.07733088933397005),
 (1622, 0.07733088933397005),
 (2312, 0.07733088933397005),
 (51, 0.07685205569389798),
 (63, 0.07685205569389798),
 (501, 0.07624928516630233),
 (634, 0.07624928516630233),
 (654, 0.07624928516630233),
 (1031, 0.07624928516630233),
 (1143, 0.07624928516630233),
 (1542, 0.07624928516630233),
 (1624, 0.07624928516630233),
 (2183, 0.07624928516630233),
 (2362, 0.07624928516630233),
 (2809, 0.07624928516630233),
 (2864, 0.07624928516630233),
 (3163, 0.07624928516630233),
 (3478, 0.07624928516630233),
 (3535, 0.07624928516630233),
 (4443, 0.07624928516630233),
 (4730, 0.07624928516630233),
 (19, 0.07566047878575344),
 (32, 0.07566047878575344),
 (572, 0.07566047878575344),
 (1934, 0.07566047878575344),
 (96, 0.07521183158458504),
 (214, 0.07521183158458504),
 (242, 0.07521183158458504),
 (680, 0.07521183158458504),
 (991, 0.07521183158458504),
 (1117, 0.07521183158458504),
 (1950, 0.07521183158458504),
 (2535, 0.07521183158458504),
 (2691, 0.07521183158458504),
 (2859, 0.07521183158458504),
 (59, 0.07508510557782777),
 (2771, 0.07452266241066098),
 (245, 0.07421560439929402),
 (587, 0.07421560439929402),
 (752, 0.07421560439929402),
 (1165, 0.07421560439929402),
 (1185, 0.07421560439929402),
 (1481, 0.07421560439929402),
 (2828, 0.07421560439929402),
 (3214, 0.07421560439929402),
 (3713, 0.07421560439929402),
 (4095, 0.07421560439929402),
 (125, 0.07405985269687691),
 (274, 0.07405985269687691),
 (313, 0.07397267214553091),
 (2173, 0.07397267214553091),
 (2418, 0.07397267214553091),
 (2720, 0.07397267214553091),
 (2797, 0.07397267214553091),
 (3077, 0.07397267214553091),
 (4111, 0.07397267214553091),
 (71, 0.07325794357582566),
 (98, 0.07325794357582566),
 (457, 0.07325794357582566),
 (885, 0.07325794357582566),
 (899, 0.07325794357582566),
 (1015, 0.07325794357582566),
 (1273, 0.07325794357582566),
 (1375, 0.07325794357582566),
 (2026, 0.07325794357582566),
 (3363, 0.07325794357582566),
 (3397, 0.07325794357582566),
 (2211, 0.0723930024686082),
 (11, 0.07233642332556181),
 (70, 0.07233642332556181),
 (97, 0.07233642332556181),
 (223, 0.07233642332556181),
 (362, 0.07233642332556181),
 (632, 0.07233642332556181),
 (788, 0.07233642332556181),
 (2171, 0.07233642332556181),
 (2243, 0.07233642332556181),
 (3067, 0.07233642332556181),
 (4067, 0.07233642332556181),
 (4135, 0.07233642332556181),
 (4463, 0.07233642332556181),
 (415, 0.07188851546895896),
 (1292, 0.07188851546895896),
 (2258, 0.07188851546895896),
 (3844, 0.07188851546895896),
 (4177, 0.07188851546895896),
 (4424, 0.07188851546895896),
 (1, 0.07144882623443115),
 (39, 0.07144882623443115),
 (53, 0.07144882623443115),
 (105, 0.07144882623443115),
 (185, 0.07144882623443115),
 (472, 0.07144882623443115),
 (503, 0.07144882623443115),
 (543, 0.07144882623443115),
 (547, 0.07144882623443115),
 (2600, 0.07144882623443115),
 (2658, 0.07144882623443115),
 (3030, 0.07144882623443115),
 (3099, 0.07144882623443115),
 (3919, 0.07144882623443115),
 (4217, 0.07144882623443115),
 (4652, 0.07144882623443115),
 (190, 0.07139443046999142),
 (138, 0.07059312080025176),
 (626, 0.07059312080025176),
 (827, 0.07059312080025176),
 (1036, 0.07059312080025176),
 (2403, 0.07059312080025176),
 (2709, 0.07059312080025176),
 (3263, 0.07059312080025176),
 (3457, 0.07059312080025176),
 (3818, 0.07059312080025176),
 (4192, 0.07059312080025176),
 (381, 0.06997114285413195),
 (2890, 0.06997114285413195),
 (3382, 0.06997114285413195),
 (4485, 0.06997114285413195),
 (37, 0.06976744186046512),
 (212, 0.06976744186046512),
 (1149, 0.06976744186046512),
 (3834, 0.06976744186046512),
 (1642, 0.06906825157099705),
 (82, 0.06897007348075543),
 (1293, 0.06897007348075543),
 (1329, 0.06897007348075543),
 (1454, 0.06897007348075543),
 (1891, 0.06897007348075543),
 (2060, 0.06897007348075543),
 (2249, 0.06897007348075543),
 (2272, 0.06897007348075543),
 (2475, 0.06897007348075543),
 (2839, 0.06897007348075543),
 (3398, 0.06897007348075543),
 (55, 0.06862971855589192),
 (229, 0.06862971855589192),
 (205, 0.06819943394704735),
 (471, 0.06819943394704735),
 (534, 0.06819943394704735),
 (536, 0.06819943394704735),
 (665, 0.06819943394704735),
 (671, 0.06819943394704735),
 (732, 0.06819943394704735),
 (908, 0.06819943394704735),
 (1009, 0.06819943394704735),
 (1352, 0.06819943394704735),
 (1629, 0.06819943394704735),
 (1631, 0.06819943394704735),
 (1640, 0.06819943394704735),
 (1672, 0.06819943394704735),
 (1773, 0.06819943394704735),
 (1778, 0.06819943394704735),
 (2029, 0.06819943394704735),
 (2795, 0.06819943394704735),
 (2924, 0.06819943394704735),
 (3406, 0.06819943394704735),
 (3994, 0.06819943394704735),
 (4006, 0.06819943394704735),
 (4193, 0.06819943394704735),
 (121, 0.06745406256199318),
 (728, 0.06745406256199318),
 (782, 0.06745406256199318),
 (1150, 0.06745406256199318),
 (3196, 0.06745406256199318),
 (4550, 0.06745406256199318),
 (488, 0.06695557088817639),
 (101, 0.06673260799501936),
 (132, 0.06673260799501936),
 (254, 0.06673260799501936),
 (983, 0.06673260799501936),
 (1195, 0.06673260799501936),
 (1463, 0.06673260799501936),
 (1709, 0.06673260799501936),
 (2064, 0.06673260799501936),
 (2143, 0.06673260799501936),
 (2371, 0.06673260799501936),
 (2896, 0.06673260799501936),
 (3008, 0.06673260799501936),
 (109, 0.06655583256397218),
 (384, 0.06655583256397218),
 (776, 0.06655583256397218),
 (1529, 0.06655583256397218),
 (1663, 0.06655583256397218),
 (2667, 0.06655583256397218),
 (3080, 0.06655583256397218),
 (3683, 0.06655583256397218),
 (3943, 0.06655583256397218),
 (4228, 0.06655583256397218),
 (4415, 0.06655583256397218),
 (4580, 0.06655583256397218),
 (4650, 0.06655583256397218),
 (657, 0.06616316935788494),
 (1998, 0.06616316935788494),
 (635, 0.0660338179744218),
 (737, 0.0660338179744218),
 (2380, 0.0660338179744218),

In [227]:
sorted(list(enumerate(similarity[0])),reverse=True, key=lambda x:x[1])[1:6]

[(1928, 0.23199266800191015),
 (1220, 0.230220812479341),
 (582, 0.2282766956670531),
 (539, 0.22264681319788207),
 (507, 0.21656228851349335)]

In [238]:
def recommend(movie):
    movie_index = new_df[new_df['title'] == movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)),reverse=True, key=lambda x:x[1])[1:6]
    
    for i in movies_list: 
        print(i[0])

In [240]:
recommend('Avatar')

1928
1220
582
539
507

In [241]:
def recommend(movie):
    movie_index = new_df[new_df['title'] == movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)),reverse=True, key=lambda x:x[1])[1:6]
    
    for i in movies_list: 
        print(new_df.iloc[i[0]].title)

In [242]:
recommend('Avatar')

Lifeforce
Aliens vs Predator: Requiem
Battle: Los Angeles
Titan A.E.
Independence Day

In [243]:
recommend('Batman Begins')

The Dark Knight
The Dark Knight Rises
Batman
Batman
Amidst the Devil's Wings

In [246]:
recommend('Inception')

Timecop
The Walk
The Helix... Loaded
Star Trek II: The Wrath of Khan
The Score